stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:24.0.5-dind
    alias: docker

.docker-login: &docker-login
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# --- BUILD JOBS ---
build-backend:
  <<: *docker-login
  stage: build
  image: docker:24.0.5
  script:
    - docker build -t $DOCKER_USERNAME/car-pooling-backend:latest ./backend
    - docker push $DOCKER_USERNAME/car-pooling-backend:latest
  only:
    - main
    - develop

build-frontend:
  <<: *docker-login
  stage: build
  image: docker:24.0.5
  script:
    - docker build --build-arg VITE_CLERK_PUBLISHABLE_KEY=$CLERK_PUBLISHABLE_KEY --build-arg VITE_API_URL=$API_SERVICE_URL -t $DOCKER_USERNAME/car-pooling-frontend:latest ./frontend
    - docker push $DOCKER_USERNAME/car-pooling-frontend:latest
  only:
    - main
    - develop

# --- DEPLOY JOBS ---
deploy-app:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - scp -o StrictHostKeyChecking=no docker-compose.yml ubuntu@$EC2_IP:/home/ubuntu/docker-compose.yml
    - ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IP "export DOCKER_USERNAME=$DOCKER_USERNAME CLERK_SECRET_KEY=$CLERK_SECRET_KEY CLIENT_URL=$CLIENT_PROD_URL; docker compose pull && docker compose up -d"
  only:
    - main
