services:
  api-gateway:
    build: .
    ports:
      - "5000:5000"
    environment:
      - API_GATEWAY_PORT=5000
      - EUREKA_URL=http://eureka-server:5001
      - AUTH_SERVICE_URL=http://auth-service:5002
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - eureka-server
    networks:
      - carpooling-network

networks:
  carpooling-network:
    external: true
